import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/global/header";
import Navbar from "@/components/global/navbar";
import { ThemeProvider } from "@/providers/theme-provider";
import { IconoirProvider } from "iconoir-react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${manrope.variable} antialiased`}>
        <IconoirProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            {children}
            <Navbar />
          </ThemeProvider>
        </IconoirProvider>
      </body>
    </html>
  );
}
